from 'amazon/opendistro-for-elasticsearch:0.8.0'

RUN echo "node.master: true" >> /usr/share/elasticsearch/config/elasticsearch.yml
RUN echo "node.data: false" >> /usr/share/elasticsearch/config/elasticsearch.yml
RUN echo "node.ingest: false" >> /usr/share/elasticsearch/config/elasticsearch.yml
RUN echo "cluster.remote.connect: false" >> /usr/share/elasticsearch/config/elasticsearch.yml